# Generated by Django 3.2.6 on 2021-09-07 00:04

import api.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organisation Name', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.CharField(help_text='Scholar User id', max_length=20, primary_key=True, serialize=False, validators=[api.validators.scholar_id_validator])),
                ('name', models.CharField(blank=True, help_text='Scholar Name', max_length=100)),
                ('organisations', models.ManyToManyField(related_name='scholars', to='api.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('citation', models.IntegerField()),
                ('scholars', models.ManyToManyField(related_name='papers', to='api.Scholar')),
            ],
        ),
    ]
